version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore(deps): update actions'
  - package-ecosystem: npm
    directory: '/'
    commit-message:
      prefix: 'chore(deps): update dependencies'
    schedule:
      interval: monthly
