name: integration
on: pull_request
concurrency:
  group: ci_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup pnpm
        uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache-dependency-path: pnpm-lock.yaml
          cache: pnpm
      - name: setup cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml', '.prettierrc.yaml') }}
          path: ./node_modules/.cache
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: build all packages
        run: pnpm build
      - name: check formatting
        run: pnpm format:ci
      - name: check commit messages
        if: github.event_name == 'pull_request'
        run: pnpm lint-commit --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
      - name: run tests
        run: pnpm test:ci
